//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 9/5/2023 5:26:47 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace WsmSystem.Erp.Core.Entities.Core
{
    public sealed partial class ApplicationInfo {

        public ApplicationInfo()
        {
            this.IdAuthorizationStatus = @"N";
            this.ClientInfos = new List<ClientInfo>();
            OnCreated();
        }

        public int Id { get; set; }

        public string ApplicationName { get; set; }

        public string ApplicationKey { get; set; }

        public DateTime? ExpireDate { get; set; }

        public bool IsActive { get; set; }

        public string IdAuthorizationStatus { get; set; }

        public string LastAction { get; set; }

        public string MakeBy { get; set; }

        public DateTime MakeDate { get; set; }

        public string UpdateBy { get; set; }

        public DateTime? UpdateDate { get; set; }

        public IList<ClientInfo> ClientInfos { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
