//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 9/5/2023 5:26:48 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using WsmSystem.Erp.Local.RepositoryInterfaces;

namespace WsmSystem.Erp.Local.RepositoryClasses
{
    public partial class EntityFrameworkRepository<T> : IRepository<T> where T : class
    {
        private Microsoft.EntityFrameworkCore.DbContext context;
        protected DbSet<T> objectSet;

        public EntityFrameworkRepository(Microsoft.EntityFrameworkCore.DbContext context)
        {

            if (context == null)
            {
                throw new ArgumentNullException("context");
            }

            this.context = context;
            this.objectSet = context.Set<T>();
        }

        public virtual IQueryable<T> All()
        {

            return objectSet;
        }

        public virtual void Add(T entity)
        {

            if (entity == null)
            {
                throw new ArgumentNullException("entity");
            }
            objectSet.Add(entity);
        }

        public virtual void Remove(T entity)
        {

            if (entity == null)
            {
                throw new ArgumentNullException("entity");
            }
            objectSet.Remove(entity);
        }

        public Microsoft.EntityFrameworkCore.DbContext Context 
        {
            get
            {
                return context;
            }
        }
    }
}
