//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 9/5/2023 5:26:48 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using WsmSystem.Erp.Local.DbContext;
using WsmSystem.Erp.Local.RepositoryInterfaces;

namespace WsmSystem.Erp.Local.RepositoryClasses
{
    public partial class EntityFrameworkUnitOfWorkFactory : IUnitOfWorkFactory
    {
        protected Microsoft.EntityFrameworkCore.DbContext context = null;

        public EntityFrameworkUnitOfWorkFactory()
            : this(new Storage())
        {
        }

        public EntityFrameworkUnitOfWorkFactory(Microsoft.EntityFrameworkCore.DbContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException("context");
            }
            this.context = context;
        }

        #region IUnitOfWorkFactory Members

        public virtual IUnitOfWork Create()
        {
            if (context == null)
                throw new InvalidOperationException("Context has not been initialized.");
            return new EntityFrameworkUnitOfWork(context);
        }
        #endregion
    }
}
