//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 9/5/2023 5:26:48 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace WsmSystem.Erp.Core.Entities
{
    public partial interface IUnitOfWorkFactory
    {
        IUnitOfWork Create();
    }
}
