//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 9/5/2023 5:26:48 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using WsmSystem.Erp.Local.Entities;

namespace WsmSystem.Erp.Local.RepositoryInterfaces
{
    public partial interface IUnitOfWork : IDisposable
    {
        IRepository<ApplicationInfo> ApplicationInfos { get; }
        IRepository<BaseLanguage> BaseLanguages { get; }
        IRepository<ClientInfo> ClientInfos { get; }
        IRepository<PhraseTag> PhraseTags { get; }
        IRepository<PhraseTagTranslation> PhraseTagTranslations { get; }
        IRepository<ItemCategory> ItemCategories { get; }
        IRepository<ItemGroup> ItemGroups { get; }
        IRepository<ItemGroupTranslation> ItemGroupTranslations { get; }
        IRepository<ItemMaster> ItemMasters { get; }
        IRepository<Uom> Uoms { get; }
        void Save();
    }
}
