// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using WsmSystem.Erp.Local.Models;

#nullable disable

namespace WsmSystem.Erp.Local.Models.Configurations
{
    public partial class AppClientConfiguration : IEntityTypeConfiguration<AppClient>
    {
        public void Configure(EntityTypeBuilder<AppClient> entity)
        {
            entity.ToTable("AppClient", "core");

            entity.Property(e => e.AppClientName).HasMaxLength(250);
            entity.Property(e => e.ApplicationKey).HasMaxLength(50);
            entity.Property(e => e.IsActive)
            .IsRequired()
            .HasDefaultValueSql("((1))")
            .HasComment("((0))");
            entity.Property(e => e.LastAction).HasMaxLength(3);
            entity.Property(e => e.MakeBy).HasMaxLength(50);
            entity.Property(e => e.MakeDate)
            .HasDefaultValueSql("(getdate())")
            .HasComment("((getdate()))");
            entity.Property(e => e.UpdateBy).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AppClient> entity);
    }
}
