// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using WsmSystem.Erp.Local.Models;

#nullable disable

namespace WsmSystem.Erp.Local.Models.Configurations
{
    public partial class ClientCompanyConfiguration : IEntityTypeConfiguration<ClientCompany>
    {
        public void Configure(EntityTypeBuilder<ClientCompany> entity)
        {
            entity.HasKey(e => e.IdClient);

            entity.ToTable("ClientCompany", "core");

            entity.Property(e => e.IdClient).ValueGeneratedNever();
            entity.Property(e => e.CompanyAddress).HasMaxLength(250);
            entity.Property(e => e.CompanyEmail).HasMaxLength(200);
            entity.Property(e => e.CompanyFax).HasMaxLength(50);
            entity.Property(e => e.CompanyFullName).HasMaxLength(400);
            entity.Property(e => e.CompanyIdentificationNo).HasMaxLength(50);
            entity.Property(e => e.CompanyLogo).HasColumnType("image");
            entity.Property(e => e.CompanyName).HasMaxLength(50);
            entity.Property(e => e.CompanyShortCode).HasMaxLength(20);
            entity.Property(e => e.CompanyTelephone).HasMaxLength(50);
            entity.Property(e => e.CompanyUrl).HasMaxLength(150);
            entity.Property(e => e.ExcludeSalaryTax).HasDefaultValueSql("((0))");
            entity.Property(e => e.ExcludeSocialSecurity).HasDefaultValueSql("((0))");
            entity.Property(e => e.IsActive)
            .IsRequired()
            .HasDefaultValueSql("((1))");
            entity.Property(e => e.LastAction).HasMaxLength(3);
            entity.Property(e => e.MakeBy).HasMaxLength(50);
            entity.Property(e => e.MakeDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.SocialSecurityNumber).HasMaxLength(20);
            entity.Property(e => e.UpdateBy).HasMaxLength(50);

            entity.HasOne(d => d.IdAppClientNavigation).WithMany(p => p.ClientCompanies)
            .HasForeignKey(d => d.IdAppClient)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ClientCompany_AppClient");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClientCompany> entity);
    }
}
