// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using WsmSystem.Erp.Local.Entities;

namespace WsmSystem.Erp.Local.Entities.Configurations
{
    public partial class AppClientConfiguration : IEntityTypeConfiguration<AppClient>
    {
        public void Configure(EntityTypeBuilder<AppClient> entity)
        {
            entity
            .ToTable("AppClient", "core")
            .ToTable(tb => tb.IsTemporal(ttb =>
                {
                    ttb.UseHistoryTable("AppClientHistory", "core");
                    ttb
                        .HasPeriodStart("StartTime")
                        .HasColumnName("StartTime");
                    ttb
                        .HasPeriodEnd("EndTime")
                        .HasColumnName("EndTime");
                }));

            entity.Property(e => e.AppClientName)
            .IsRequired()
            .HasMaxLength(250);
            entity.Property(e => e.ApplicationKey).HasMaxLength(50);
            entity.Property(e => e.IsActive)
            .IsRequired()
            .HasDefaultValueSql("((1))")
            .HasComment("((0))");
            entity.Property(e => e.LastAction)
            .IsRequired()
            .HasMaxLength(3);
            entity.Property(e => e.MakeBy)
            .IsRequired()
            .HasMaxLength(50);
            entity.Property(e => e.MakeDate)
            .HasDefaultValueSql("(getdate())")
            .HasComment("((getdate()))");
            entity.Property(e => e.UpdateBy).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AppClient> entity);
    }
}
