// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using WsmSystem.Erp.Local.Entities;

namespace WsmSystem.Erp.Local.Entities.Configurations
{
    public partial class NoticeConfiguration : IEntityTypeConfiguration<Notice>
    {
        public void Configure(EntityTypeBuilder<Notice> entity)
        {
            entity.HasKey(e => new { e.IdClient, e.Id });

            entity
            .ToTable("Notice", "core")
            .ToTable(tb => tb.IsTemporal(ttb =>
                {
                    ttb.UseHistoryTable("NoticeHistory", "core");
                    ttb
                        .HasPeriodStart("StartTime")
                        .HasColumnName("StartTime");
                    ttb
                        .HasPeriodEnd("EndTime")
                        .HasColumnName("EndTime");
                }));

            entity.Property(e => e.AttachedFileUrl)
            .HasMaxLength(250)
            .IsUnicode(false);
            entity.Property(e => e.IdAuthorizationStatus)
            .IsRequired()
            .HasMaxLength(1)
            .HasDefaultValueSql("('N')");
            entity.Property(e => e.LastAction)
            .IsRequired()
            .HasMaxLength(3)
            .IsUnicode(false);
            entity.Property(e => e.MakeBy)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.NoticeBody)
            .IsRequired()
            .IsUnicode(false);
            entity.Property(e => e.PublishedDate).HasColumnType("datetime");
            entity.Property(e => e.Title)
            .IsRequired()
            .HasMaxLength(100)
            .IsUnicode(false);
            entity.Property(e => e.UpdateBy)
            .HasMaxLength(50)
            .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Notice> entity);
    }
}
