// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using WsmSystem.Erp.Local.Entities;

namespace WsmSystem.Erp.Local.Entities.Configurations
{
    public partial class PermissionNamingPolicyConfiguration : IEntityTypeConfiguration<PermissionNamingPolicy>
    {
        public void Configure(EntityTypeBuilder<PermissionNamingPolicy> entity)
        {
            entity.HasKey(e => new { e.IdClient, e.Id });

            entity
            .ToTable("PermissionNamingPolicy", "core")
            .ToTable(tb => tb.IsTemporal(ttb =>
                {
                    ttb.UseHistoryTable("PermissionNamingPolicyHistory", "core");
                    ttb
                        .HasPeriodStart("StartTime")
                        .HasColumnName("StartTime");
                    ttb
                        .HasPeriodEnd("EndTime")
                        .HasColumnName("EndTime");
                }));

            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.Property(e => e.IdAuthorizationStatus)
            .IsRequired()
            .HasMaxLength(1);
            entity.Property(e => e.IsActive)
            .IsRequired()
            .HasDefaultValueSql("((1))");
            entity.Property(e => e.LastAction)
            .IsRequired()
            .HasMaxLength(3)
            .HasDefaultValueSql("('ADD')");
            entity.Property(e => e.LevelName)
            .IsRequired()
            .HasMaxLength(50);
            entity.Property(e => e.MakeBy)
            .IsRequired()
            .HasMaxLength(50);
            entity.Property(e => e.UpdateBy).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PermissionNamingPolicy> entity);
    }
}
