// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using WsmSystem.Erp.Local.Entities;

namespace WsmSystem.Erp.Local.Entities.Configurations
{
    public partial class PhraseTagTranslationConfiguration : IEntityTypeConfiguration<PhraseTagTranslation>
    {
        public void Configure(EntityTypeBuilder<PhraseTagTranslation> entity)
        {
            entity.HasKey(e => new { e.IdClient, e.Id });

            entity
            .ToTable("PhraseTagTranslation", "core")
            .ToTable(tb => tb.IsTemporal(ttb =>
                {
                    ttb.UseHistoryTable("PhraseTagTranslationHistory", "core");
                    ttb
                        .HasPeriodStart("StartTime")
                        .HasColumnName("StartTime");
                    ttb
                        .HasPeriodEnd("EndTime")
                        .HasColumnName("EndTime");
                }));

            entity.Property(e => e.Expression).HasMaxLength(250);
            entity.Property(e => e.IdAuthorizationStatus)
            .IsRequired()
            .HasMaxLength(1)
            .HasDefaultValueSql("('N')");
            entity.Property(e => e.IsActive)
            .IsRequired()
            .HasDefaultValueSql("((1))");
            entity.Property(e => e.LastAction)
            .IsRequired()
            .HasMaxLength(50);
            entity.Property(e => e.MakeBy)
            .IsRequired()
            .HasMaxLength(50);
            entity.Property(e => e.MakeDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdateBy).HasMaxLength(50);

            entity.HasOne(d => d.IdNavigation).WithMany(p => p.PhraseTagTranslation)
            .HasForeignKey(d => new { d.IdClient, d.IdLanguage })
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_PhraseTagTranslation_BaseLanguage");

            entity.HasOne(d => d.Id1).WithMany(p => p.PhraseTagTranslation)
            .HasForeignKey(d => new { d.IdClient, d.IdPhraseTag })
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_PhraseTagTranslation_PhraseTag");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PhraseTagTranslation> entity);
    }
}
