// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using WsmSystem.Erp.Local.Entities;

namespace WsmSystem.Erp.Local.Entities.Configurations
{
    public partial class UserWiseGroupMappingConfiguration : IEntityTypeConfiguration<UserWiseGroupMapping>
    {
        public void Configure(EntityTypeBuilder<UserWiseGroupMapping> entity)
        {
            entity.HasKey(e => new { e.IdClient, e.Id });

            entity
            .ToTable("UserWiseGroupMapping", "core")
            .ToTable(tb => tb.IsTemporal(ttb =>
                {
                    ttb.UseHistoryTable("UserWiseGroupMappingHistory", "core");
                    ttb
                        .HasPeriodStart("StartTime")
                        .HasColumnName("StartTime");
                    ttb
                        .HasPeriodEnd("EndTime")
                        .HasColumnName("EndTime");
                }));

            entity.Property(e => e.Id).ValueGeneratedOnAdd();
            entity.Property(e => e.IdAuthorizationStatus)
            .IsRequired()
            .HasMaxLength(1)
            .HasDefaultValueSql("('N')");
            entity.Property(e => e.IsActive)
            .IsRequired()
            .HasDefaultValueSql("((1))");
            entity.Property(e => e.LastAction)
            .IsRequired()
            .HasMaxLength(3);
            entity.Property(e => e.MakeBy)
            .IsRequired()
            .HasMaxLength(50);
            entity.Property(e => e.UpdateBy).HasMaxLength(50);

            entity.HasOne(d => d.IdNavigation).WithMany(p => p.UserWiseGroupMapping)
            .HasForeignKey(d => new { d.IdClient, d.IdUser })
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_UserWiseGroupMapping_Users");

            entity.HasOne(d => d.Id1).WithMany(p => p.UserWiseGroupMapping)
            .HasForeignKey(d => new { d.IdClient, d.IdUserGroup })
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_UserWiseGroupMapping_UserGroup");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserWiseGroupMapping> entity);
    }
}
