// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using WsmSystem.Erp.Local.Entities;

namespace WsmSystem.Erp.Local.Entities.Configurations
{
    public partial class UsersConfiguration : IEntityTypeConfiguration<Users>
    {
        public void Configure(EntityTypeBuilder<Users> entity)
        {
            entity.HasKey(e => new { e.IdClient, e.Id });

            entity
            .ToTable("Users", "core")
            .ToTable(tb => tb.IsTemporal(ttb =>
                {
                    ttb.UseHistoryTable("UsersHistory", "core");
                    ttb
                        .HasPeriodStart("StartTime")
                        .HasColumnName("StartTime");
                    ttb
                        .HasPeriodEnd("EndTime")
                        .HasColumnName("EndTime");
                }));

            entity.Property(e => e.AccessLevel).HasMaxLength(4);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.EmployeeId).HasMaxLength(50);
            entity.Property(e => e.IdAuthorizationStatus)
            .IsRequired()
            .HasMaxLength(1)
            .HasDefaultValueSql("('N')");
            entity.Property(e => e.IsActive)
            .IsRequired()
            .HasDefaultValueSql("((1))");
            entity.Property(e => e.LastAction)
            .IsRequired()
            .HasMaxLength(50);
            entity.Property(e => e.MakeBy)
            .IsRequired()
            .HasMaxLength(50);
            entity.Property(e => e.Password).HasMaxLength(500);
            entity.Property(e => e.PasswordSalt).HasMaxLength(500);
            entity.Property(e => e.UpdateBy).HasMaxLength(50);
            entity.Property(e => e.UserFullName).HasMaxLength(100);
            entity.Property(e => e.UserName)
            .IsRequired()
            .HasMaxLength(50);

            entity.HasOne(d => d.IdNavigation).WithMany(p => p.Users)
            .HasForeignKey(d => new { d.IdClient, d.IdRole })
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Users_UserRole");

            entity.HasOne(d => d.Id1).WithMany(p => p.Users)
            .HasForeignKey(d => new { d.IdClient, d.IdUserLanguage })
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Users_BaseLanguage");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Users> entity);
    }
}
