// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using WsmSystem.Erp.Local.Models.Configurations;
#nullable enable

namespace WsmSystem.Erp.Local.Models;

public partial class Storage : DbContext
{
    public Storage(DbContextOptions<Storage> options)
        : base(options)
    {
    }

    public virtual DbSet<AppClient>? AppClients { get; set; }

    public virtual DbSet<BaseLanguage>? BaseLanguages { get; set; }

    public virtual DbSet<ClientCompany>? ClientCompanies { get; set; }

    public virtual DbSet<EmailTemplate>? EmailTemplates { get; set; }

    public virtual DbSet<PhraseTag>? PhraseTags { get; set; }

    public virtual DbSet<PhraseTagTranslation>? PhraseTagTranslations { get; set; }

    public virtual DbSet<SmtpClient>? SmtpClients { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.AppClientConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.BaseLanguageConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ClientCompanyConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EmailTemplateConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PhraseTagConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PhraseTagTranslationConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SmtpClientConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
