//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 9/5/2023 5:26:47 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace WsmSystem.Erp.Local.Entities
{
    public partial class ItemMaster {

        public ItemMaster()
        {
            OnCreated();
        }

        public string SystemItemID { get; set; }

        public string NewItemCode { get; set; }

        public string OldItemCode { get; set; }

        public string SystemProductGroupID { get; set; }

        public string SystemItemCategoryID { get; set; }

        public string EItemDescription { get; set; }

        public string PItemDescription { get; set; }

        public string EShortItemDescription { get; set; }

        public string PShortItemDescription { get; set; }

        public string UOM { get; set; }

        public decimal? QuantityPerPieceUnit { get; set; }

        public string PieceUnitID { get; set; }

        public decimal? QuantityPerUnit { get; set; }

        public string UnitID { get; set; }

        public string SKURange { get; set; }

        public string ItemSubType { get; set; }

        public decimal? ReOrderLevel { get; set; }

        public decimal? MinSalesPrice { get; set; }

        public decimal? MaxSalesPrice { get; set; }

        public decimal? TotalStockInHand { get; set; }

        public string Remarks { get; set; }

        public bool? IsMixItem { get; set; }

        public string StdContFeet { get; set; }

        public decimal? StdContQty { get; set; }

        public decimal? CapacityPercent { get; set; }

        public byte[] ItemImage { get; set; }

        public string SecondarySystemItemID { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
