//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 9/5/2023 5:26:47 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace WsmSystem.Erp.Local.Entities
{
    public partial class ItemCategory {

        public ItemCategory()
        {
            OnCreated();
        }

        public string SystemItemCategoryID { get; set; }

        public string ItemProductID { get; set; }

        public string ItemCategoryID { get; set; }

        public string EItemCategoryDesc { get; set; }

        public string PItemCategoryDesc { get; set; }

        public string ItemCategoryShortCode { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
