//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 5/22/2022 12:09:13 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace WsmSystem.Erp.Domain.Entities.V1.Securities
{
    public class AppClient : BaseEntity
    {
        public virtual int Id { get; private set; }

        public virtual string AppClientName { get; private set; } = null!;

        public virtual string? ApplicationKey { get; private set; }

        public virtual DateTime? ExpireDate { get; private set; }

        public virtual IList<ClientInfo> ClientInfos { get; private set; } = new List<ClientInfo>();
    }
}
