//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 5/22/2022 12:09:13 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace WsmSystem.Erp.Domain.Entities.V1.Securities
{
    public class RoleWiseScreenPermission : BaseEntity
    {
        public RoleWiseScreenPermission(int idRole, int idClient, int screenCode, string? accessRight, string lastAction, Screen screen, UserRole userRole)
        {
            IdRole = idRole;
            IdClient = idClient;
            ScreenCode = screenCode;
            AccessRight = accessRight;
            LastAction = lastAction ?? throw new ArgumentNullException(nameof(lastAction));
            Screen = screen ?? throw new ArgumentNullException(nameof(screen));
            UserRole = userRole ?? throw new ArgumentNullException(nameof(userRole));
        }

        public virtual int IdRole { get; set; }

        public virtual int IdClient { get; set; }

        public virtual int ScreenCode { get; set; }

        public virtual string? AccessRight { get; set; }

        public virtual string LastAction { get; set; }

        public virtual Screen Screen { get; set; }

        public virtual UserRole UserRole { get; set; }

    }

}
