//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 5/22/2022 12:09:13 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using WsmSystem.Erp.Domain.Common;

namespace WsmSystem.Erp.Domain.Entities.V1.Securities
{
    public class Screen : AuditableEntity
    {
        public Screen() => RoleWiseScreenPermissions = new List<RoleWiseScreenPermission>();

        public virtual int IdClient { get; set; }

        public virtual int ScreenCode { get; set; }

        public virtual string ScreenName { get; set; }

        public virtual int IdModule { get; set; }

        public virtual int IdSubModule { get; set; }

        public virtual int IdSubModuleSection { get; set; }

        public virtual short? Ordinal { get; set; }

        public virtual string ScreenUri { get; set; }

        public virtual string ScreenDescription { get; set; }

        public virtual bool IsRequiredForApproval { get; set; }

        public virtual bool IsFinancialScreen { get; set; }

        public virtual string IconName { get; set; }

        public virtual bool IsActive { get; set; }

        public virtual string LastAction { get; set; }

        public virtual IList<RoleWiseScreenPermission> RoleWiseScreenPermissions { get; set; }

        public virtual SubModuleSection SubModuleSection { get; set; }

    }

}
