//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 5/22/2022 12:09:13 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using WsmSystem.Erp.Domain.Common;

namespace WsmSystem.Erp.Domain.Entities.V1.Securities
{
    public class Screen : BaseEntity
    {
        public Screen(int idClient, int screenCode, string screenName, int idModule, int idSubModule, int idSubModuleSection, short? ordinal, string screenUri, string screenDescription, bool isRequiredForApproval, bool isFinancialScreen, string iconName, bool isActive, string lastAction, IList<RoleWiseScreenPermission> roleWiseScreenPermissions, SubModuleSection subModuleSection)
        {
            IdClient = idClient;
            ScreenCode = screenCode;
            ScreenName = screenName ?? throw new ArgumentNullException(nameof(screenName));
            IdModule = idModule;
            IdSubModule = idSubModule;
            IdSubModuleSection = idSubModuleSection;
            Ordinal = ordinal;
            ScreenUri = screenUri ?? throw new ArgumentNullException(nameof(screenUri));
            ScreenDescription = screenDescription ?? throw new ArgumentNullException(nameof(screenDescription));
            IsRequiredForApproval = isRequiredForApproval;
            IsFinancialScreen = isFinancialScreen;
            IconName = iconName ?? throw new ArgumentNullException(nameof(iconName));
            IsActive = isActive;
            LastAction = lastAction ?? throw new ArgumentNullException(nameof(lastAction));
            RoleWiseScreenPermissions = roleWiseScreenPermissions ?? throw new ArgumentNullException(nameof(roleWiseScreenPermissions));
            SubModuleSection = subModuleSection ?? throw new ArgumentNullException(nameof(subModuleSection));
        }

        public virtual int IdClient { get; set; }

        public virtual int ScreenCode { get; set; }

        public virtual string ScreenName { get; set; }

        public virtual int IdModule { get; set; }

        public virtual int IdSubModule { get; set; }

        public virtual int IdSubModuleSection { get; set; }

        public virtual short? Ordinal { get; set; }

        public virtual string ScreenUri { get; set; }

        public virtual string ScreenDescription { get; set; }

        public virtual bool IsRequiredForApproval { get; set; }

        public virtual bool IsFinancialScreen { get; set; }

        public virtual string IconName { get; set; }

        public virtual bool IsActive { get; set; }

        public virtual string LastAction { get; set; }

        public virtual IList<RoleWiseScreenPermission> RoleWiseScreenPermissions { get; set; }

        public virtual SubModuleSection SubModuleSection { get; set; }

    }

}
