//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 5/22/2022 12:09:13 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace WsmSystem.Erp.Domain.Entities.V1.Securities
{
    public class UserRole : BaseEntity
    {
        public UserRole(int idClient, int id, string roleName, string? roleDescription, IList<RoleWiseScreenPermission> roleWiseScreenPermissions, IList<UserGroupRoleLink> userGroupRoleLinks, IList<UserInfo> userInfos, IList<UserRoleResourceLink> userRoleResourceLinks)
        {
            IdClient = idClient;
            Id = id;
            RoleName = roleName ?? throw new ArgumentNullException(nameof(roleName));
            RoleDescription = roleDescription;
            RoleWiseScreenPermissions = roleWiseScreenPermissions ?? throw new ArgumentNullException(nameof(roleWiseScreenPermissions));
            UserGroupRoleLinks = userGroupRoleLinks ?? throw new ArgumentNullException(nameof(userGroupRoleLinks));
            UserInfos = userInfos ?? throw new ArgumentNullException(nameof(userInfos));
            UserRoleResourceLinks = userRoleResourceLinks ?? throw new ArgumentNullException(nameof(userRoleResourceLinks));
        }

        public virtual int IdClient { get; set; }

        public virtual int Id { get; set; }

        public virtual string RoleName { get; set; }

        public virtual string? RoleDescription { get; set; }

        public virtual IList<RoleWiseScreenPermission> RoleWiseScreenPermissions { get; set; } = new List<RoleWiseScreenPermission>();

        public virtual IList<UserGroupRoleLink> UserGroupRoleLinks { get; set; } = new List<UserGroupRoleLink>();

        public virtual IList<UserInfo> UserInfos { get; set; } = new List<UserInfo>();

        public virtual IList<UserRoleResourceLink> UserRoleResourceLinks { get; set; } = new List<UserRoleResourceLink>();
    }
}