//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 5/22/2022 12:09:13 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace WsmSystem.Erp.Domain.Entities.V1.Securities
{
    public class UserGroupLink : BaseEntity
    {
        public virtual int IdClient { get; set; }

        public virtual int Id { get; set; }

        public virtual int IdUser { get; set; }

        public virtual int IdUserGroup { get; set; }

        public virtual UserInfo UserInfo { get; set; } = null!;

        public virtual UserGroup UserGroup { get; set; } = null!;
    }
}
