//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 5/22/2022 12:09:13 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace WsmSystem.Erp.Domain.Entities.V1.Securities
{
    public class UserGroupRoleLink : BaseEntity
    {
        public UserGroupRoleLink(int idClient, int id, int idUserGroup, int idUserRole, string lastAction, UserGroup userGroup, UserRole userRole)
        {
            IdClient = idClient;
            Id = id;
            IdUserGroup = idUserGroup;
            IdUserRole = idUserRole;
            LastAction = lastAction ?? throw new ArgumentNullException(nameof(lastAction));
            UserGroup = userGroup ?? throw new ArgumentNullException(nameof(userGroup));
            UserRole = userRole ?? throw new ArgumentNullException(nameof(userRole));
        }

        public virtual int IdClient { get; set; }

        public virtual int Id { get; set; }

        public virtual int IdUserGroup { get; set; }

        public virtual int IdUserRole { get; set; }

        public virtual string LastAction { get; set; }

        public virtual UserGroup UserGroup { get; set; }

        public virtual UserRole UserRole { get; set; }

    }

}
