//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 5/22/2022 12:09:13 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using WsmSystem.Erp.Domain.Common;

namespace WsmSystem.Erp.Domain.Entities.V1.Securities
{
    public class UserInfo : BaseEntity
    {
        public UserInfo() => UserGroupLinks = new List<UserGroupLink>();

        public virtual int IdClient { get; set; }

        public virtual int Id { get; set; }

        public virtual string AccessLevel { get; set; }

        public virtual string UserName { get; set; }

        public virtual string UserFullName { get; set; }

        public virtual string UserPassword { get; set; }

        public virtual string PasswordSalt { get; set; }

        public virtual int? IdRole { get; set; }

        public virtual bool IsActive { get; set; }

        public virtual string UserEmail { get; set; }

        public virtual bool IsLockedOut { get; set; }

        public virtual bool? ChangePassword { get; set; }

        public virtual string LastAction { get; set; }

        public virtual IList<UserGroupLink> UserGroupLinks { get; set; }

        public virtual UserRole UserRole { get; set; }

    }

}
