//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 5/22/2022 12:09:13 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace WsmSystem.Erp.Domain.Entities.V1.Securities
{
    public class UserInfo : BaseEntity
    {
        public UserInfo(int idClient, int id, string? accessLevel, string userName, string? userFullName, string userPassword, string? passwordSalt, int? idRole, string? userEmail, bool isLockedOut, bool? changePassword, IList<UserGroupLink> userGroupLinks, UserRole userRole)
        {
            IdClient = idClient;
            Id = id;
            AccessLevel = accessLevel;
            UserName = userName ?? throw new ArgumentNullException(nameof(userName));
            UserFullName = userFullName;
            UserPassword = userPassword ?? throw new ArgumentNullException(nameof(userPassword));
            PasswordSalt = passwordSalt;
            IdRole = idRole;
            UserEmail = userEmail;
            IsLockedOut = isLockedOut;
            ChangePassword = changePassword;
            UserGroupLinks = userGroupLinks ?? throw new ArgumentNullException(nameof(userGroupLinks));
            UserRole = userRole ?? throw new ArgumentNullException(nameof(userRole));
        }

        public virtual int IdClient { get; set; }

        public virtual int Id { get; set; }

        public virtual string? AccessLevel { get; set; }

        public virtual string UserName { get; set; }

        public virtual string? UserFullName { get; set; }

        public virtual string UserPassword { get; set; }

        public virtual string? PasswordSalt { get; set; }

        public virtual int? IdRole { get; set; }

        public virtual string? UserEmail { get; set; }

        public virtual bool IsLockedOut { get; set; }

        public virtual bool? ChangePassword { get; set; }

        public virtual IList<UserGroupLink> UserGroupLinks { get; set; } = new List<UserGroupLink>();

        public virtual UserRole UserRole { get; set; }

    }

}
