//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 5/22/2022 12:09:13 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using WsmSystem.Erp.Domain.Common;

namespace WsmSystem.Erp.Domain.Entities.V1.Securities
{
    public class UserGroupLink : BaseEntity
    {
        public UserGroupLink(int idClient, int id, int idUser, int idUserGroup, bool isActive, string lastAction, UserInfo userInfo, UserGroup userGroup)
        {
            IdClient = idClient;
            Id = id;
            IdUser = idUser;
            IdUserGroup = idUserGroup;
            IsActive = isActive;
            LastAction = lastAction ?? throw new ArgumentNullException(nameof(lastAction));
            UserInfo = userInfo ?? throw new ArgumentNullException(nameof(userInfo));
            UserGroup = userGroup ?? throw new ArgumentNullException(nameof(userGroup));
        }

        public virtual int IdClient { get; set; }

        public virtual int Id { get; set; }

        public virtual int IdUser { get; set; }

        public virtual int IdUserGroup { get; set; }

        public virtual bool IsActive { get; set; }

        public virtual string LastAction { get; set; }

        public virtual UserInfo UserInfo { get; set; }

        public virtual UserGroup UserGroup { get; set; }

    }

}
