//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 5/22/2022 12:09:13 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using WsmSystem.Erp.Domain.Common;

namespace WsmSystem.Erp.Domain.Entities.V1.Securities
{
    public class UserRole : AuditableEntity
    {
        public UserRole()
        {
            RoleWiseScreenPermissions = new List<RoleWiseScreenPermission>();
            UserGroupRoleLinks = new List<UserGroupRoleLink>();
            UserInfos = new List<UserInfo>();
            UserRoleResourceLinks = new List<UserRoleResourceLink>();

        }

        public virtual int IdClient { get; set; }

        public virtual int Id { get; set; }

        public virtual string RoleName { get; set; }

        public virtual string RoleDescription { get; set; }

        public virtual bool IsActive { get; set; }

        public virtual string LastAction { get; set; }

        public virtual IList<RoleWiseScreenPermission> RoleWiseScreenPermissions { get; set; }

        public virtual IList<UserGroupRoleLink> UserGroupRoleLinks { get; set; }

        public virtual IList<UserInfo> UserInfos { get; set; }

        public virtual IList<UserRoleResourceLink> UserRoleResourceLinks { get; set; }

    }

}
