//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 7/21/2023 10:48:21 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WsmSystemModel
{
    public partial class EntityFrameworkUnitOfWork : IUnitOfWork
    {
        protected DbContext context = null;

        IAppClientRepository _AppClients;

        IAppClientHistoryRepository _AppClientHistories;

        IBaseLanguageRepository _BaseLanguages;

        IBaseLanguageHistoryRepository _BaseLanguageHistories;

        IClientCompanyRepository _ClientCompanies;

        IClientCompanyHistoryRepository _ClientCompanyHistories;

        IEmailTemplateRepository _EmailTemplates;

        IEmailTemplateHistoryRepository _EmailTemplateHistories;

        IHttpMethodRepository _HttpMethods;

        IHttpMethodHistoryRepository _HttpMethodHistories;

        IModuleRepository _Modules;

        IModuleHistoryRepository _ModuleHistories;

        INoticeRepository _Notices;

        INoticeHistoryRepository _NoticeHistories;

        IPermissionNamingPolicyRepository _PermissionNamingPolicies;

        IPermissionNamingPolicyHistoryRepository _PermissionNamingPolicyHistories;

        IPhraseTagRepository _PhraseTags;

        IPhraseTagHistoryRepository _PhraseTagHistories;

        IPhraseTagTranslationRepository _PhraseTagTranslations;

        IPhraseTagTranslationHistoryRepository _PhraseTagTranslationHistories;

        IRoleScreenLinkRepository _RoleScreenLinks;

        IRoleScreenLinkHistoryRepository _RoleScreenLinkHistories;

        IScreenRepository _Screens;

        IScreenHistoryRepository _ScreenHistories;

        ISectionRepository _Sections;

        ISectionHistoryRepository _SectionHistories;

        ISmtpClientRepository _SmtpClients;

        ISmtpClientHistoryRepository _SmtpClientHistories;

        ISubModuleRepository _SubModules;

        ISubModuleHistoryRepository _SubModuleHistories;

        IUserGroupRepository _UserGroups;

        IUserGroupHistoryRepository _UserGroupHistories;

        IUserGroupWiseRoleMappingRepository _UserGroupWiseRoleMappings;

        IUserGroupWiseRoleMappingHistoryRepository _UserGroupWiseRoleMappingHistories;

        IUserResourceRepository _UserResources;

        IUserResourceHistoryRepository _UserResourceHistories;

        IUserRoleRepository _UserRoles;

        IUserRoleHistoryRepository _UserRoleHistories;

        IUserRoleWiseResourceMappingRepository _UserRoleWiseResourceMappings;

        IUserRoleWiseResourceMappingHistoryRepository _UserRoleWiseResourceMappingHistories;

        IUserRepository _Users;

        IUsersHistoryRepository _UsersHistories;

        IUserWiseGroupMappingRepository _UserWiseGroupMappings;

        IUserWiseGroupMappingHistoryRepository _UserWiseGroupMappingHistories;

        public EntityFrameworkUnitOfWork()
            : this(new WsmSystemModel())
        {
        }

        public EntityFrameworkUnitOfWork(DbContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException("context");
            }
            this.context = context;
        }

        public DbContext Context
        {
            get
            {
                return context;
            }
        }

        protected virtual void CloseContext()
        {
            if (context != null)
            {
                context.Dispose();
                context = null;
            }
        }

        #region IDisposable Methods

        private bool disposed = false;

        protected virtual void Dispose(bool disposing)
        {
            if (!this.disposed)
            {
                if (disposing)
                {
                    CloseContext();
                }
            }
            this.disposed = true;
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        #endregion

        #region IUnitOfWork Members

        public IAppClientRepository AppClients {
          get {
            if (_AppClients == null)
              _AppClients = new AppClientRepository((WsmSystemModel)context);
            return _AppClients;
          }
        }

        public IAppClientHistoryRepository AppClientHistories {
          get {
            if (_AppClientHistories == null)
              _AppClientHistories = new AppClientHistoryRepository((WsmSystemModel)context);
            return _AppClientHistories;
          }
        }

        public IBaseLanguageRepository BaseLanguages {
          get {
            if (_BaseLanguages == null)
              _BaseLanguages = new BaseLanguageRepository((WsmSystemModel)context);
            return _BaseLanguages;
          }
        }

        public IBaseLanguageHistoryRepository BaseLanguageHistories {
          get {
            if (_BaseLanguageHistories == null)
              _BaseLanguageHistories = new BaseLanguageHistoryRepository((WsmSystemModel)context);
            return _BaseLanguageHistories;
          }
        }

        public IClientCompanyRepository ClientCompanies {
          get {
            if (_ClientCompanies == null)
              _ClientCompanies = new ClientCompanyRepository((WsmSystemModel)context);
            return _ClientCompanies;
          }
        }

        public IClientCompanyHistoryRepository ClientCompanyHistories {
          get {
            if (_ClientCompanyHistories == null)
              _ClientCompanyHistories = new ClientCompanyHistoryRepository((WsmSystemModel)context);
            return _ClientCompanyHistories;
          }
        }

        public IEmailTemplateRepository EmailTemplates {
          get {
            if (_EmailTemplates == null)
              _EmailTemplates = new EmailTemplateRepository((WsmSystemModel)context);
            return _EmailTemplates;
          }
        }

        public IEmailTemplateHistoryRepository EmailTemplateHistories {
          get {
            if (_EmailTemplateHistories == null)
              _EmailTemplateHistories = new EmailTemplateHistoryRepository((WsmSystemModel)context);
            return _EmailTemplateHistories;
          }
        }

        public IHttpMethodRepository HttpMethods {
          get {
            if (_HttpMethods == null)
              _HttpMethods = new HttpMethodRepository((WsmSystemModel)context);
            return _HttpMethods;
          }
        }

        public IHttpMethodHistoryRepository HttpMethodHistories {
          get {
            if (_HttpMethodHistories == null)
              _HttpMethodHistories = new HttpMethodHistoryRepository((WsmSystemModel)context);
            return _HttpMethodHistories;
          }
        }

        public IModuleRepository Modules {
          get {
            if (_Modules == null)
              _Modules = new ModuleRepository((WsmSystemModel)context);
            return _Modules;
          }
        }

        public IModuleHistoryRepository ModuleHistories {
          get {
            if (_ModuleHistories == null)
              _ModuleHistories = new ModuleHistoryRepository((WsmSystemModel)context);
            return _ModuleHistories;
          }
        }

        public INoticeRepository Notices {
          get {
            if (_Notices == null)
              _Notices = new NoticeRepository((WsmSystemModel)context);
            return _Notices;
          }
        }

        public INoticeHistoryRepository NoticeHistories {
          get {
            if (_NoticeHistories == null)
              _NoticeHistories = new NoticeHistoryRepository((WsmSystemModel)context);
            return _NoticeHistories;
          }
        }

        public IPermissionNamingPolicyRepository PermissionNamingPolicies {
          get {
            if (_PermissionNamingPolicies == null)
              _PermissionNamingPolicies = new PermissionNamingPolicyRepository((WsmSystemModel)context);
            return _PermissionNamingPolicies;
          }
        }

        public IPermissionNamingPolicyHistoryRepository PermissionNamingPolicyHistories {
          get {
            if (_PermissionNamingPolicyHistories == null)
              _PermissionNamingPolicyHistories = new PermissionNamingPolicyHistoryRepository((WsmSystemModel)context);
            return _PermissionNamingPolicyHistories;
          }
        }

        public IPhraseTagRepository PhraseTags {
          get {
            if (_PhraseTags == null)
              _PhraseTags = new PhraseTagRepository((WsmSystemModel)context);
            return _PhraseTags;
          }
        }

        public IPhraseTagHistoryRepository PhraseTagHistories {
          get {
            if (_PhraseTagHistories == null)
              _PhraseTagHistories = new PhraseTagHistoryRepository((WsmSystemModel)context);
            return _PhraseTagHistories;
          }
        }

        public IPhraseTagTranslationRepository PhraseTagTranslations {
          get {
            if (_PhraseTagTranslations == null)
              _PhraseTagTranslations = new PhraseTagTranslationRepository((WsmSystemModel)context);
            return _PhraseTagTranslations;
          }
        }

        public IPhraseTagTranslationHistoryRepository PhraseTagTranslationHistories {
          get {
            if (_PhraseTagTranslationHistories == null)
              _PhraseTagTranslationHistories = new PhraseTagTranslationHistoryRepository((WsmSystemModel)context);
            return _PhraseTagTranslationHistories;
          }
        }

        public IRoleScreenLinkRepository RoleScreenLinks {
          get {
            if (_RoleScreenLinks == null)
              _RoleScreenLinks = new RoleScreenLinkRepository((WsmSystemModel)context);
            return _RoleScreenLinks;
          }
        }

        public IRoleScreenLinkHistoryRepository RoleScreenLinkHistories {
          get {
            if (_RoleScreenLinkHistories == null)
              _RoleScreenLinkHistories = new RoleScreenLinkHistoryRepository((WsmSystemModel)context);
            return _RoleScreenLinkHistories;
          }
        }

        public IScreenRepository Screens {
          get {
            if (_Screens == null)
              _Screens = new ScreenRepository((WsmSystemModel)context);
            return _Screens;
          }
        }

        public IScreenHistoryRepository ScreenHistories {
          get {
            if (_ScreenHistories == null)
              _ScreenHistories = new ScreenHistoryRepository((WsmSystemModel)context);
            return _ScreenHistories;
          }
        }

        public ISectionRepository Sections {
          get {
            if (_Sections == null)
              _Sections = new SectionRepository((WsmSystemModel)context);
            return _Sections;
          }
        }

        public ISectionHistoryRepository SectionHistories {
          get {
            if (_SectionHistories == null)
              _SectionHistories = new SectionHistoryRepository((WsmSystemModel)context);
            return _SectionHistories;
          }
        }

        public ISmtpClientRepository SmtpClients {
          get {
            if (_SmtpClients == null)
              _SmtpClients = new SmtpClientRepository((WsmSystemModel)context);
            return _SmtpClients;
          }
        }

        public ISmtpClientHistoryRepository SmtpClientHistories {
          get {
            if (_SmtpClientHistories == null)
              _SmtpClientHistories = new SmtpClientHistoryRepository((WsmSystemModel)context);
            return _SmtpClientHistories;
          }
        }

        public ISubModuleRepository SubModules {
          get {
            if (_SubModules == null)
              _SubModules = new SubModuleRepository((WsmSystemModel)context);
            return _SubModules;
          }
        }

        public ISubModuleHistoryRepository SubModuleHistories {
          get {
            if (_SubModuleHistories == null)
              _SubModuleHistories = new SubModuleHistoryRepository((WsmSystemModel)context);
            return _SubModuleHistories;
          }
        }

        public IUserGroupRepository UserGroups {
          get {
            if (_UserGroups == null)
              _UserGroups = new UserGroupRepository((WsmSystemModel)context);
            return _UserGroups;
          }
        }

        public IUserGroupHistoryRepository UserGroupHistories {
          get {
            if (_UserGroupHistories == null)
              _UserGroupHistories = new UserGroupHistoryRepository((WsmSystemModel)context);
            return _UserGroupHistories;
          }
        }

        public IUserGroupWiseRoleMappingRepository UserGroupWiseRoleMappings {
          get {
            if (_UserGroupWiseRoleMappings == null)
              _UserGroupWiseRoleMappings = new UserGroupWiseRoleMappingRepository((WsmSystemModel)context);
            return _UserGroupWiseRoleMappings;
          }
        }

        public IUserGroupWiseRoleMappingHistoryRepository UserGroupWiseRoleMappingHistories {
          get {
            if (_UserGroupWiseRoleMappingHistories == null)
              _UserGroupWiseRoleMappingHistories = new UserGroupWiseRoleMappingHistoryRepository((WsmSystemModel)context);
            return _UserGroupWiseRoleMappingHistories;
          }
        }

        public IUserResourceRepository UserResources {
          get {
            if (_UserResources == null)
              _UserResources = new UserResourceRepository((WsmSystemModel)context);
            return _UserResources;
          }
        }

        public IUserResourceHistoryRepository UserResourceHistories {
          get {
            if (_UserResourceHistories == null)
              _UserResourceHistories = new UserResourceHistoryRepository((WsmSystemModel)context);
            return _UserResourceHistories;
          }
        }

        public IUserRoleRepository UserRoles {
          get {
            if (_UserRoles == null)
              _UserRoles = new UserRoleRepository((WsmSystemModel)context);
            return _UserRoles;
          }
        }

        public IUserRoleHistoryRepository UserRoleHistories {
          get {
            if (_UserRoleHistories == null)
              _UserRoleHistories = new UserRoleHistoryRepository((WsmSystemModel)context);
            return _UserRoleHistories;
          }
        }

        public IUserRoleWiseResourceMappingRepository UserRoleWiseResourceMappings {
          get {
            if (_UserRoleWiseResourceMappings == null)
              _UserRoleWiseResourceMappings = new UserRoleWiseResourceMappingRepository((WsmSystemModel)context);
            return _UserRoleWiseResourceMappings;
          }
        }

        public IUserRoleWiseResourceMappingHistoryRepository UserRoleWiseResourceMappingHistories {
          get {
            if (_UserRoleWiseResourceMappingHistories == null)
              _UserRoleWiseResourceMappingHistories = new UserRoleWiseResourceMappingHistoryRepository((WsmSystemModel)context);
            return _UserRoleWiseResourceMappingHistories;
          }
        }

        public IUserRepository Users {
          get {
            if (_Users == null)
              _Users = new UserRepository((WsmSystemModel)context);
            return _Users;
          }
        }

        public IUsersHistoryRepository UsersHistories {
          get {
            if (_UsersHistories == null)
              _UsersHistories = new UsersHistoryRepository((WsmSystemModel)context);
            return _UsersHistories;
          }
        }

        public IUserWiseGroupMappingRepository UserWiseGroupMappings {
          get {
            if (_UserWiseGroupMappings == null)
              _UserWiseGroupMappings = new UserWiseGroupMappingRepository((WsmSystemModel)context);
            return _UserWiseGroupMappings;
          }
        }

        public IUserWiseGroupMappingHistoryRepository UserWiseGroupMappingHistories {
          get {
            if (_UserWiseGroupMappingHistories == null)
              _UserWiseGroupMappingHistories = new UserWiseGroupMappingHistoryRepository((WsmSystemModel)context);
            return _UserWiseGroupMappingHistories;
          }
        }

        public virtual void Save()
        {
            if (context == null)
                throw new InvalidOperationException("Context has not been initialized.");
            context.SaveChanges();
        }

        #endregion
    }
}
