//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 7/21/2023 10:48:21 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;

namespace WsmSystemModel
{
    public partial class UserGroupWiseRoleMappingHistoryRepository : EntityFrameworkRepository<UserGroupWiseRoleMappingHistory>, IUserGroupWiseRoleMappingHistoryRepository
    {
        public UserGroupWiseRoleMappingHistoryRepository(WsmSystemModel context)
            : base(context)
        {
        }

        public virtual ICollection<UserGroupWiseRoleMappingHistory> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual UserGroupWiseRoleMappingHistory GetByKey()
        {
            return objectSet.SingleOrDefault(e => );
        }

        public new WsmSystemModel Context 
        {
            get
            {
                return (WsmSystemModel)base.Context;
            }
        }
    }
}
