// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WsmSystem.Erp.Local.Models;

public partial class AppClient
{
    public int Id { get; set; }

    public string AppClientName { get; set; } = null!;

    public string? ApplicationKey { get; set; }

    public DateTime? ExpireDate { get; set; }

    /// <summary>
    /// ((0))
    /// </summary>
    public bool? IsActive { get; set; }

    public string LastAction { get; set; } = null!;

    public string MakeBy { get; set; } = null!;

    /// <summary>
    /// ((getdate()))
    /// </summary>
    public DateTime MakeDate { get; set; }

    public string? UpdateBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ICollection<ClientCompany> ClientCompanies { get; set; } = new List<ClientCompany>();
}